"""Add Category model

Revision ID: 03530fc3d5ee
Revises: 1b54891532a2
Create Date: 2025-06-01 22:26:20.137694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03530fc3d5ee'
down_revision = '1b54891532a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
